### ISSUE TITLE
Error checking x509 extension section v3_req even with req_ext=false

### ISSUE THREAD

**Issue by gdlx** [voxpupuli/puppet-openssl#230]
I'm getting this issue when trying to create an x509 cert:
```
Error: Execution of '/usr/bin/openssl req -config /etc/puppetlabs/puppet/ssl/certs/myserver.domain.com.cnf -new -x509 -days 3650 -key /etc/puppetlabs/puppet/ssl/private_keys/myserver.domain.com.pem -out /etc/puppetlabs/puppet/ssl/certs/myserver.domain.com.pem -extensions v3_req' returned 1: Error checking x509 extension section v3_req
```

It seems to be caused by this line: https://github.com/voxpupuli/puppet-openssl/blob/master/lib/puppet/provider/x509_cert/openssl.rb#L101

The condition is different than here: https://github.com/voxpupuli/puppet-openssl/blob/master/lib/puppet/provider/x509_cert/openssl.rb#L77

And it seems to incorrectly interpret the `false` value (default).

Removing `!= :false` as in line 77 fixes the issue for me.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 8.9.0
- Ruby: 3.1.2
- Distribution: Debian 12
- Module version: 4.1.0

## How to reproduce (e.g Puppet code you use)

```puppet
  $fqdn = $facts['networking']['fqdn'].downcase
  $puppet_ssl_path = '/etc/puppetlabs/puppet/ssl'
  $ssl_key_path = "${puppet_ssl_path}/private_keys/${fqdn}.pem"
  $ssl_cert_path = "${puppet_ssl_path}/certs/${fqdn}.pem"
  $ssl_cfg_path = "${puppet_ssl_path}/certs/${fqdn}.cnf"

  ssl_pkey { $ssl_key_path:
    ensure => 'present',
    size   => 4096,
  }

  -> openssl::config { $ssl_cfg_path:
    ensure     => 'present',
    commonname => $fqdn,
  }

  -> x509_cert { $ssl_cert_path:
    ensure      => 'present',
    private_key => $ssl_key_path,
    template    => $ssl_cfg_path,
    days        => 3650,
    force       => true,
  }
```

**Comment by rtib** [comment]
https://github.com/voxpupuli/puppet-openssl/blob/9230d0b7f98f299b03bb759a65c257c7ab700465/lib/puppet/provider/x509_cert/openssl.rb#L101
🤦 
Each time I see such conditionals I feel George Boole just died again, a very painful death.

The issue is that in Ruby `false` is a boolean value, while `:false` is just trying to mimic a boolean, however, it is a symbol. It was not a problem until another ugly hack was cleaned up with [268ae1c](https://github.com/voxpupuli/puppet-openssl/commit/268ae1ce1113e6d421819896f7c4ca90eac0da35#diff-76763da33e8ccd3c126699a4bb340fcc6ae861721a53da60aa885a2ec6d13478) which made `:req_ext` a real boolean parameter, thus unable to match a symbol like `:false`.

**Comment by zilchms** [comment]
Mea culpa for the bools/symbol interpolation.... This whole module needs some serious work unfortunately. I want to try to get some tests going for the upcoming week and start fixing it up again (failed / introduced some bugs the last time....)

**Comment by rtib** [comment]
@zilchms the PR is already filed and ready for review.
